# Config for the right index finger1
[Fingers]
[[motors]]
finger_name="r_finger1"
motor1.id = 1
motor1.offset = -0.0523599
motor1.invert = false
motor1.model = "STS3032"
motor2.id = 2
motor2.offset = -0.0174533
motor2.invert = false
motor2.model = "STS3032"
[[motors]]
finger_name="r_finger2"
motor1.id = 3
motor1.offset = 0.122173
motor1.invert = false
motor1.model = "STS3032"
motor2.id = 4
motor2.offset = 0.10472
motor2.invert = false
motor2.model = "STS3032"
[[motors]]
finger_name="r_finger3"
motor1.id = 5
motor1.offset = 0.0349066
motor1.invert = false
motor1.model = "STS3032"
motor2.id = 6
motor2.offset = 0.0349066
motor2.invert = false
motor2.model = "STS3032"
[[motors]]
finger_name="r_finger4"
motor1.id = 7
motor1.offset = 0.139626
motor1.invert = false
motor1.model = "STS3032"
motor2.id = 8
motor2.offset = -0.139626
motor2.invert = false
motor2.model = "STS3032"
